Repository Pinelog-Studios/AdditionalGuns, pull requests merged in 2022-07, with the labels that each got.

#49 Added bullet casings
  src/main/resources/assets/additionalguns/models/item/casing_heavy.json
  src/main/resources/assets/additionalguns/models/item/casing_long.json
  src/main/resources/assets/additionalguns/models/item/casing_medium.json
  src/main/resources/assets/additionalguns/models/item/casing_short.json
  src/main/resources/assets/additionalguns/models/item/casing_small.json
  src/main/resources/assets/additionalguns/models/item/casing_special.json
Labels: enhancement, new content

#55 Updated, added, removed and/or fixed all sounds
  src/main/resources/assets/additionalguns/sounds/item/ak1_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/ak2_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/aos_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/aug_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/awm_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/banshee_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/deagle_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/fn2000_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/heavy_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/heavy_suppression.ogg
  src/main/resources/assets/additionalguns/sounds/item/intsup.ogg
  src/main/resources/assets/additionalguns/sounds/item/light_suppression.ogg
  src/main/resources/assets/additionalguns/sounds/item/m1014_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/m1911_enchanted.ogg
  src/main/resources/assets/additionalguns/sounds/item/m1911_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/m1911_suppressed.ogg
  src/main/resources/assets/additionalguns/sounds/item/mac10_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/magnum_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/mammoth_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/medium_suppression.ogg
  src/main/resources/assets/additionalguns/sounds/item/mp7a2_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/ots03_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/p250_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/pistol_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/pistol_suppressed.ogg
  src/main/resources/assets/additionalguns/sounds/item/pp19_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/ravensclaw_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/rifle_suppressed.ogg
  src/main/resources/assets/additionalguns/sounds/item/ssg08_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/vector_fire.ogg
  src/main/resources/assets/additionalguns/sounds/item/vector_suppressed.ogg
Labels: enhancement

#61 0.7.0 Weapon Additions - CasualNoLifer
  src/main/resources/assets/additionalguns/models/item/m1911.json
  src/main/resources/assets/additionalguns/models/item/magnum.json
  src/main/resources/assets/additionalguns/textures/item/m1911.png
  src/main/resources/data/additionalguns/guns/m1911.json
  src/main/resources/data/additionalguns/guns/magnum.json
Labels: new content

#67 0.7.1 bugfixes
  src/main/resources/data/additionalguns/guns/ak104.json
  src/main/resources/data/additionalguns/guns/ak105.json
  src/main/resources/data/additionalguns/guns/ak12.json
  src/main/resources/data/additionalguns/guns/ak74.json
  src/main/resources/data/additionalguns/guns/ak74m.json
  src/main/resources/data/additionalguns/guns/akm.json
  src/main/resources/data/additionalguns/guns/akm_custom.json
  src/main/resources/data/additionalguns/guns/aks74u.json
Labels: bugfix

#70 🤖 Issue tracker support bot
  .github/workflows/dependency.yml
  .github/workflows/eol.yml
  .github/workflows/legacy_version.yml
  .github/workflows/off-topic.yml
Labels: enhancement

#77 0.7.2 Bugfixes (but it should work this time)
  src/main/resources/assets/additionalguns/models/item/aug.json
  src/main/resources/assets/additionalguns/models/item/magnum.json
  src/main/resources/assets/additionalguns/models/item/usp.json
  src/main/resources/data/additionalguns/guns/aug.json
  src/main/resources/data/additionalguns/guns/awm.json
  src/main/resources/data/additionalguns/guns/fn2000.json
  src/main/resources/data/additionalguns/guns/magnum.json
  src/main/resources/data/additionalguns/guns/ssg08.json
  src/main/resources/data/additionalguns/guns/usp.json
Labels: bugfix
